version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    container_name: my_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: my_app
    depends_on:
      - db

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli.Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=my_db
    volumes:
      - ./tmp:/var/lib/mysql/
    container_name: my_db

  pmy:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - UPLOAD_LIMIT=64M
    container_name: my_pmy

  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
